# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - DadsTaxi(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALSDB964D86 }}

    - name: add build time to healthcheck
      run: |
        echo "Build time: $(date)" >> public/healthcheck.txt

    - name: Run Azure webapp deploy action using current context
      uses: azure/webapps-deploy@v2
      with:
        app-name: DadsTaxi
        slot-name: Production
        package: .

    - name: setup regional logo AU
      run: cp icons/logo-au.png logo.png
    - name: Run Azure webapp deploy action using current context 
      uses: azure/webapps-deploy@v2
      with:
        app-name: DadsTaxi-au
        slot-name: Production
        package: .

    - name: setup regional logo US
      run: cp icons/logo-us.png logo.png
    - name: Run Azure webapp deploy action using current context 
      uses: azure/webapps-deploy@v2
      with:
        app-name: DadsTaxi-us
        slot-name: Production
        package: .

    - name: setup regional logo EU
      run: cp icons/logo-eu.png logo.png
    - name: Run Azure webapp deploy action using current context 
      uses: azure/webapps-deploy@v2
      with:
        app-name: DadsTaxi-westeurope
        slot-name: Production
        package: .